"""
From ChatGPT:
Sure, here's an example of how you can use the bootstrap to estimate a 95% confidence interval for the median of your data:

Create a large number of bootstrap samples by randomly resampling your original data with replacement. Each bootstrap sample should have the same size as your original data set.

For each bootstrap sample, calculate the median.

From the distribution of medians obtained from the bootstrap samples, calculate the 2.5th and 97.5th percentiles to obtain a 95% confidence interval.

Here's the Python code to implement this using the numpy and scipy libraries:
"""

import numpy as np
from scipy.stats import scoreatpercentile

# input data
data = np.array(
    [
        71,
        82,
        72,
        74,
        69,
        68,
        72,
        72,
        69,
        68,
        68,
        75,
        75,
        78,
        77,
        76,
        76,
        75,
        69,
        69,
        70,
        70,
        78,
        72,
        74,
        68,
        70,
        70,
        73,
        76,
        66,
        74,
        72,
        69,
        78,
        70,
        74,
        70,
    ]
)

# number of bootstrap samples
# np.random.seed() is a function from the NumPy library that sets the random seed for the NumPy random number generator.
# Pseudo-random numbers generated by a computer are not truly random because they are generated using an algorithm that follows a deterministic process. However, by setting a seed value, we can control the starting point of the algorithm and produce a sequence of numbers that appears to be random and is reproducible.
# By setting a seed value before generating random numbers, we can ensure that the same sequence of random numbers is generated every time we run the code. This is useful for testing and reproducibility, especially in scientific research where we want to ensure that our results can be independently verified.
nboot = 10000

# set seed for reproducibility
np.random.seed(123)

# bootstrap sampling
med_boot = np.empty(nboot)
for i in range(nboot):
    idx = np.random.choice(len(data), len(data), replace=True)
    med_boot[i] = np.median(data[idx])

# 95% confidence interval for the median
lower_ci = scoreatpercentile(med_boot, 2.5)
upper_ci = scoreatpercentile(med_boot, 97.5)

# report results
median = np.median(data)
uncertainty = (upper_ci - lower_ci) / 2
print(f"Median: {median:.3f}")
print(f"Median Uncertainty: ±{uncertainty:.3f}")
